build_from: ghcr.io/home-assistant/amd64-addon-base:latest
name: "Goblin MagicToDo Integration"
version: "1.0.2"
slug: "goblin_todo_addon"
description: >
  Integrates Goblin.tools Magic ToDo with Home Assistant.
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: services
boot: auto
host_network: true
homeassistant_api: false
options:
  username: "your-username"
  password: "your-password"
schema:
  username:
    type: string
  password:
    type: string
