build_from: python:3.11-slim
name: "Goblin MagicToDo Integration"
version: "1.0.1"
slug: "goblin_todo_addon"
description: >-
  Integrates Goblin.tools Magic ToDo with Home Assistant.
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: "services"
boot: "auto"
host_network: true
homeassistant_api: false
options:
  username: "your-username"
  password: "your-password"
schema:
  username:
    type: str
  password:
    type: str
